kafka:
  bootstrapAddress: localhost:29092 #change to kafka for docker
  topics:
    order-service-outbox: order-service-outbox
    product-service-outbox: product-service-outbox


  group:
    id: app.1

logging:
  level:
    root: info
